apiVersion: v1
kind: Service
metadata:
  name: capstone
  namespace: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: capstone